# Generated by Django 4.1.2 on 2023-02-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
