# Generated by Django 4.1.2 on 2023-03-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_viewer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myrating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='myrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MyList',
        ),
        migrations.DeleteModel(
            name='Myrating',
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
